/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/cgu` | `/cgu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/delete-account` | `/delete-account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/mentions-legales` | `/mentions-legales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/privacy-policy` | `/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/tracking` | `/tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(legal)'}/cgu` | `/cgu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(legal)'}/delete-account` | `/delete-account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(legal)'}/mentions-legales` | `/mentions-legales`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(legal)'}/privacy-policy` | `/privacy-policy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(legal)'}/tracking` | `/tracking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(legal)'}/cgu${`?${string}` | `#${string}` | ''}` | `/cgu${`?${string}` | `#${string}` | ''}` | `${'/(legal)'}/delete-account${`?${string}` | `#${string}` | ''}` | `/delete-account${`?${string}` | `#${string}` | ''}` | `${'/(legal)'}/mentions-legales${`?${string}` | `#${string}` | ''}` | `/mentions-legales${`?${string}` | `#${string}` | ''}` | `${'/(legal)'}/privacy-policy${`?${string}` | `#${string}` | ''}` | `/privacy-policy${`?${string}` | `#${string}` | ''}` | `${'/(legal)'}/tracking${`?${string}` | `#${string}` | ''}` | `/tracking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MapView${`?${string}` | `#${string}` | ''}` | `/MapView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/page2${`?${string}` | `#${string}` | ''}` | `/page2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/cgu` | `/cgu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/delete-account` | `/delete-account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/mentions-legales` | `/mentions-legales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/privacy-policy` | `/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(legal)'}/tracking` | `/tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
