/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CustomTabBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../store/store`; params?: Router.UnknownInputParams; } | { pathname: `/../store/slices/authSlice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CustomTabBar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/store`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/slices/authSlice`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/Button${`?${string}` | `#${string}` | ''}` | `/../components/Input${`?${string}` | `#${string}` | ''}` | `/../components/CustomTabBar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/page2${`?${string}` | `#${string}` | ''}` | `/page2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../hooks/use-theme-color${`?${string}` | `#${string}` | ''}` | `/../hooks/use-color-scheme.web${`?${string}` | `#${string}` | ''}` | `/../store/store${`?${string}` | `#${string}` | ''}` | `/../store/slices/authSlice${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MapView${`?${string}` | `#${string}` | ''}` | `/MapView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CustomTabBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../store/store`; params?: Router.UnknownInputParams; } | { pathname: `/../store/slices/authSlice`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
