/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RideHistoryCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/EditProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/PaymentSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/RideHistorySection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/TravelModeSelector`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/MapViewWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/RideSelector`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RideHistoryCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/profile/ProfileHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/profile/EditProfileModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/profile/PaymentSection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/profile/RideHistorySection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/map/TravelModeSelector`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/map/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/map/MapViewWrapper`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/map/RideSelector`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/RideHistoryCard${`?${string}` | `#${string}` | ''}` | `/../components/profile/ProfileHeader${`?${string}` | `#${string}` | ''}` | `/../components/profile/EditProfileModal${`?${string}` | `#${string}` | ''}` | `/../components/profile/PaymentSection${`?${string}` | `#${string}` | ''}` | `/../components/profile/RideHistorySection${`?${string}` | `#${string}` | ''}` | `/../components/map/TravelModeSelector${`?${string}` | `#${string}` | ''}` | `/../components/map/SearchBar${`?${string}` | `#${string}` | ''}` | `/../components/map/MapViewWrapper${`?${string}` | `#${string}` | ''}` | `/../components/map/RideSelector${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MapView${`?${string}` | `#${string}` | ''}` | `/MapView${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/page2${`?${string}` | `#${string}` | ''}` | `/page2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RideHistoryCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/ProfileHeader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/EditProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/PaymentSection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/profile/RideHistorySection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/TravelModeSelector`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/MapViewWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/../components/map/RideSelector`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapView` | `/MapView`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/page2` | `/page2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
